<a href="https://colab.research.google.com/github/putricha/college-machine-learning/blob/main/PraktikumBAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def norm_data(data):

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0,data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)


  return data


  # contoh penggunaan
  data=[10, 11, 12, 14, 16]
  n_data = norm_data(data)
  print(n_data)




In [ ]:
def norm_data(data):
  '''
  Melakukan normalisasi data.

  Parameters:
      data (list): Data yang akan dinormalisasi.

  Returns:
      list: Data yang sudah dinormalisasi.

  '''

  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)

  return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data) # Melakukan normalisasi
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6)
np.set_printoptions(suppress=True)  #hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan, scikit-learn hanya menerima input
# dalam bentuk -dimensional array

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]


# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print("Data Asli")
print(data)

# Mendefinisikan obyek MinMaxScaler
scaler = MinMaxScaler()

#Transformasikan data

scaled = scaler.fit_transform(data)
print("Data Normalisasi")
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6) #bulatkan 4 angkat koma
np.set_printoptions(suppress=True)

#kita akan membentuk data
#hal ini dikarenakan, scikit-learn hanya menerima input
#dalam bentuk -dimensional array

data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print("Data Asli")
print(data)

scaler = StandardScaler()
# Transformasikan data
scaled = scaler.fit_transform(data)
print("Data Standarisasi")
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


In [ ]:
from sklearn.preprocessing import OrdinalEncoder

# Inisiasi Obyek Ordinal Encoder
oe = OrdinalEncoder()

# Definisikan data
# dalam bentuk 2d

# setiap kategori diberi nilai unik sebagai tanda pengenal

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)
print("Data Asli")
print(data)

print('Datwa Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Datwa Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


In [ ]:
from  sklearn.preprocessing import  OneHotEncoder

# inisial objek ordinal encoder

ohe = OneHotEncoder()

# definisikan data
# dalam bentuk 2d

# setiap kategori diberi nilai unik sebagai tanda pengenal

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# transformasi ordinal encoder

transform_ohe= ohe.fit_transform(data)
print("Data Asli")
print(data)

print("Data Transformasi One Hot Encoder")
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One Hot Encoder
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Inisiasi obyek Ordinal encooder
de = OneHotEncoder(drop='first')

# definisikan data
#  dalam bentuk 2d

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

# transformasi ordinal encoder

transform_de = de.fit_transform(data)
print("Data Asli")
print(data)

print("Data Transformasi One-Hot Encoding")
print(transform_de.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [ ]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi obyek TFidVectorizer

vect= TfidfVectorizer(stop_words='english')

# pembobotan tf idf

resp = vect.fit_transform(corpus)
print(resp)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [ ]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi obyek TFidVectorizer

vect= TfidfVectorizer(stop_words='english')

# pembobotan tf idf

resp = vect.fit_transform(corpus)
print(resp)
print(resp.toarray())

# cetak token hasil stopword
print('Hasil Token')
print(vect.get_feature_names_out())



  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0

In [ ]:
import pandas as pd
data = ('/content/drive/MyDrive/MACHINE LEARNING/corpus.txt')

with open(data, 'r') as file:
    corpus = file.readlines()

from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi obyek TFidVectorizer

vect= TfidfVectorizer(stop_words='english')

# pembobotan tf idf

resp = vect.fit_transform(corpus)
print(resp)
print(resp.toarray())

# cetak token hasil stopword
print('Hasil Token')
print(vect.get_feature_names_out())


  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.       0.      ]
 [0.       0.       0.       0.670092 0